# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  host: <%= ENV.fetch("DATABASE_HOST") { 'localhost' } %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  port: 5432
  adapter: postgresql
  username: <%= ENV["JOURNAL_APP_DATABASE_USERNAME"] %>
  password: <%= ENV["JOURNAL_APP_DATABASE_PASSWORD"] %>

development:
  <<: *default
  database: journal_app_development

test:
  <<: *default
  database: journal_app_test

production:
  <<: *default
  database: journal_app_production
